// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBevnt7UA-cGG5wy_pB1wFE86YTGZdiAxA',
    appId: '1:1002941394407:web:e9c86cabc30eb8af2ae142',
    messagingSenderId: '1002941394407',
    projectId: 'catwash',
    authDomain: 'catwash.firebaseapp.com',
    storageBucket: 'catwash.appspot.com',
    measurementId: 'G-G74R9Y52CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeKOhQwNx4FrWHSLdRDkmumccWpLwdAPE',
    appId: '1:1002941394407:android:83469fff215beb622ae142',
    messagingSenderId: '1002941394407',
    projectId: 'catwash',
    storageBucket: 'catwash.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBihhXcW6C3I3hU7QaYXtt25rgTY6pwI1Q',
    appId: '1:1002941394407:ios:18a3effad54225142ae142',
    messagingSenderId: '1002941394407',
    projectId: 'catwash',
    storageBucket: 'catwash.appspot.com',
    iosBundleId: 'com.example.flutterCarwash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBihhXcW6C3I3hU7QaYXtt25rgTY6pwI1Q',
    appId: '1:1002941394407:ios:18a3effad54225142ae142',
    messagingSenderId: '1002941394407',
    projectId: 'catwash',
    storageBucket: 'catwash.appspot.com',
    iosBundleId: 'com.example.flutterCarwash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBevnt7UA-cGG5wy_pB1wFE86YTGZdiAxA',
    appId: '1:1002941394407:web:5374eb8749784bec2ae142',
    messagingSenderId: '1002941394407',
    projectId: 'catwash',
    authDomain: 'catwash.firebaseapp.com',
    storageBucket: 'catwash.appspot.com',
    measurementId: 'G-PQJWXC47DE',
  );
}
